web:
  bindAddress: "0.0.0.0"
  port: 8080
  webDirectory: 

logger:
  encoding: console
  level:
    core: debug
    storage: debug
    metrics: debug

database:
  storage: mongodb
  metrics: influxdb_v2

databases:
  - name: mongodb
    database: mydb
    uri: "***"
  
  - name: influxdb_v2
    uri: http://localhost:9999
    token: "***"
    username: john
    password: password
    organization: mycontroller-org
    bucket: mycontroller
    batch_size: 