name: Publish images

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Build and publish images
      run: ./scripts/build.sh
