name: publish executables
on:
  push:
    branches: [master]
    tags: ["v*"]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: checkout backend repository
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: setup web console repository
        run: ./scripts/setup_web_console.sh

      - name: cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: build web console
        run: ./scripts/build_web_console.sh

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: build bundles
        run: ./scripts/generate_executables.sh

      - name: add timestamp file
        run: |
          echo `date -u +'%Y%m%d%H%M%S'` > builds/timestamp.txt  
          echo `date -u +'%Y-%m-%dT%H:%M:%S%:z'` >> builds/timestamp.txt

      - name: copy executables to the remote system
        uses: appleboy/scp-action@master
        if: github.ref == 'refs/heads/master' # executes only for master branch
        with:
          host: ${{ secrets.MYC_SERVER_ADDRESS }}
          username: ${{ secrets.MYC_SERVER_USER }}
          key: ${{ secrets.MYC_SERVER_KEY }}
          passphrase: ${{ secrets.MYC_SERVER_PASSPHRASE }}
          source: "builds/*.tar.gz,builds/*.zip,builds/timestamp.txt"
          target: "github/v2/master"
          rm: true
          strip_components: 1

      - name: Update release notes and executables
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # executes only for new release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            builds/*.tar.gz
            builds/*.zip

      - name: Update executables for master branch changes
        if: startsWith(github.ref, 'refs/heads/master') # executes only for changes in master
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: master
          prerelease: true
          title: "master branch build - Pre Release"
          files: |
            builds/*.tar.gz
            builds/*.zip
